name: Plugin CI With pnpm

on:
  workflow_call:
    inputs:
      lint:
        description: 'Set to true to run linting scripts.'
        required: false
        default: false
        type: boolean
      lint-node-version:
        description: 'Version of node to install for lint script.'
        required: false
        default: '16'
        type: string
      lint-script:
        description: 'pnpm run lint script'
        required: false
        default: 'pnpm run lint'
        type: string
      install-script:
        description: 'pnpm run install script'
        required: false
        default: 'pnpm install --ignore-scripts'
        type: string
      test-script:
        description: 'pnpm run test script'
        required: false
        default: 'pnpm run test'
        type: string
      pnpm-version:
        description: 'install pnpm version'
        required: false
        default: '7.4.0'
        type: string

jobs:
  linter:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Skip lint
        if: ${{ inputs.lint == false}}
        run: exit 0

      - name: Check out repo
        if: ${{ inputs.lint == true}}
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node
        if: ${{ inputs.lint == true}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.lint-node-version }}

      - name: Install dependencies
        if: ${{ inputs.lint == true}}
        run: ${{ inputs.install-script }}

      - name: Lint code
        if: ${{ inputs.lint == true}}
        run: ${{ inputs.lint-script }}

  test:
    name: Test
    needs: linter
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ inputs.pnpm-version}}

      - name: Install dependencies
        run: ${{ inputs.install-script }}

      - name: Run tests
        run: ${{ inputs.test-script }}
